version: '2'
services:
  nginx:
    image: armdocker.seli.gic.ericsson.se/proj-openstack_queuing_solution/oqs_baseline:${BASELINE_VERSION}
    restart: always
    ports:
     - "443:443"
     - "80:80"
    depends_on:
     - client
     - express
     - swagger
     - helpdocs
    volumes:
     - ./nginx/production.conf:/etc/nginx/conf.d/default.conf
     - ./config/sslcerts:/etc/nginx/certs
     - baseline_version:/etc/nginx/conf.d/version-info

  client:
    image: armdocker.seli.gic.ericsson.se/proj-openstack_queuing_solution/oqs_client:${CLIENT_VERSION}
    restart: always
    volumes:
     - client_version:/usr/share/nginx/version-info

  express:
    image: armdocker.seli.gic.ericsson.se/proj-openstack_queuing_solution/oqs_server:${SERVER_VERSION}
    restart: always
    environment:
     - DB_1_PORT_27017_TCP_ADDR=mongodb
     - LDAP_URL=${LDAP_URL}
     - SEARCH_FILTER=${SEARCH_FILTER}
     - BASE_DN_LIST=${BASE_DN_LIST}
     - UPGRADE_TOOL_URL=${UPGRADE_TOOL_URL}
     - OQS_EMAIL_ADDRESS=${OQS_EMAIL_ADDRESS}
     - DTT_EMAIL_ADDRESS=${DTT_EMAIL_ADDRESS}
     - DTT_EMAIL_PASSWORD=${DTT_EMAIL_PASSWORD}
     - TEAM_EMAIL=${TEAM_EMAIL}
    depends_on:
     - mongodb
    volumes:
     - baseline_version:/usr/src/app/version-info/baseline
     - client_version:/usr/src/app/version-info/client
     - helpdocs_version:/usr/src/app/version-info/helpdocs
     - apidocs_version:/usr/src/app/version-info/apidocs

  mongodb:
    image: armdocker.seli.gic.ericsson.se/dockerhub-ericsson-remote/mongo:4.0.14
    restart: always
    volumes:
     - mongodb_data:/data/db
     - mongodb_logs:/var/log/mongodb

  swagger:
    image: armdocker.seli.gic.ericsson.se/proj-openstack_queuing_solution/oqs_apidocs:${APIDOCS_VERSION}
    restart: always
    environment:
     - API_URL=/apidocs/swagger.json
    volumes:
     - apidocs_version:/usr/src/app/version-info

  helpdocs:
    image: armdocker.seli.gic.ericsson.se/proj-openstack_queuing_solution/oqs_helpdocs:${HELPDOCS_VERSION}
    restart: always
    volumes:
     - helpdocs_version:/opt/helpdocs/version-info

volumes:
  baseline_version:
  client_version:
  apidocs_version:
  helpdocs_version:
  mongodb_data:
  mongodb_logs:
